set -g @powerkit_theme 'tokyo-night'
set -g @powerkit_theme_variant 'night'

set -g @powerkit_plugins "datetime,battery,cpu,memory,hostname"

set -g @powerkit_separator_style "normal"

set -g @powerkit_status_interval "5"

set -g @powerkit_theme_selector_key "T"
set -g @powerkit_reload_config_key "R"
