#!/bin/bash

source "$CONFIG_DIR/colors.sh" # Loads all defined colors

# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar position=top height=40 blur_radius=10 color=$BAR_COLOR

update_freq=2
##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  padding_left=2
  padding_right=2
  icon.font="SF Pro:Semibold:12.0"
  label.font="SF Pro:Semibold:12.0"
  icon.color=$WHITE
  background.color=$ITEM_BG_COLOR
  background.corner_radius=5
  background.height=24
  label.color=$WHITE
  icon.padding_left=2
  icon.padding_right=5
  label.padding_left=5
  label.padding_right=4
)
sketchybar --default "${default[@]}"

##### Adding Left Items #####
source $ITEM_DIR/aerospace.sh
source $ITEM_DIR/front_app.sh

##### Adding Right Items #####
source $ITEM_DIR/calendar.sh
source $ITEM_DIR/keyboard.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/cpu.sh
source $ITEM_DIR/slack.sh

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
