unbind r
bind r source-file ~/.config/tmux/tmux.conf

set -g prefix C-s

set -g mouse on

set-option -g status-position top

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# List of plugins
set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'fabioluciano/tmux-powerkit'

source-file ~/.config/tmux/themes/tokyo-night.conf

# Initialize and run tpm
run '~/.config/tmux/plugins/tpm/tpm'


